version: "3"
services:
  zookeeper:
    image: confluent/zookeeper
    ports:
      - "2181:2181"
    networks:
      - back
  kafka:
    image: confluent/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeper:2181"
#      KAFKA_ADVERTISED_HOSST_NAME: "kafka"
#      KAFKA_ADVERTISED_PORT: "9092"
#      KAFKA_ZOOKEEPER_CONNEcT: "zookeeper:2181"
    depends_on:
      - zookeeper
    networks:
      - back
  test:
    build: test
    volumes:
      - "./test:/code"
    depends_on:
      - kafka
    networks:
      - back
networks:
  back: